### ISSUE TITLE
Bug in CPU training (related to TensorFlow)?

### ISSUE THREAD

**Issue by tim5go** [indiejoseph/doc-han-att#2]
As I observed, there will be an out-of-vocabulary error throwing out when using the "embedding_lookup"
Error looks like:

InvalidArgumentError (see above for traceback): indices[0,1,3] = 6501 is not in [0, 6342)
         [[Node: model_1/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@model/embedding"], validate_
indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](model/embedding/read, _recv_model_1/inputs_0)]]

See https://github.com/geek-ai/irgan/issues/9

Nothing wrong with your code, it sounds like a known issue in Tensorflow (CPU version)

**Comment by indiejoseph** [comment]
are you obtain the TFrecord training file via [data_helper](https://github.com/indiejoseph/doc-han-att/blob/master/data_helpers.py#L149) ? Line 149 used `dict.get` any OOV indexes will replace with 0(UNK index), so there no way has any index out of specified `vocab.pkl`.

**Comment by tim5go** [comment]
I used: python train.py
So I assumed it was already using data_helper.
I will try to switch it to a GPU environment to see if the problem still persists.

BTW, may I know the corpus size of your char-rnn model, it seems that it is quite RAM-consuming.
For a 2GB Apple Daily raw text, there will be a spike of 60GB consumption. (although the consumption will go down later)

It will be nicer if I know your original corpus size ><"

**Comment by tim5go** [comment]
After changing the line:
https://github.com/indiejoseph/doc-han-att/blob/master/model.py#L30
from cpu to gpu, the error goes away.

^^

**Comment by indiejoseph** [comment]
i used <1GB Apple Daily news text to train char-rnn LM.
it is so weird that i was successfully training this model with CPU, what is your tensorflow version?

**Comment by tim5go** [comment]
Um...maybe one of the reason is that my vocabulary size is smaller than yours i.e. 6790 
I only got 6342 from a 300MB corpus
Also, I am using tensorflow 1.1 in Python 3.
